- Applied a modified version of patch by Radu Greab, fixing a   security problem in temporary file creation algorithm of   genbasedir, and improving the temporary directory creation   algorithm of gpg method. - Fixed bug in Ademar's patch, introduced by myself.

diff --git a/tools/genbasedir b/tools/genbasedir
--- a/tools/genbasedir
+++ b/tools/genbasedir
@@ -54,6 +54,7 @@ updateinfo=
 progress=
 flat=
 defaultkey=
+srcidxdir=
 
 # bloat is necessary for non-Conectiva distros, at least RH,
 # because they use file dependencies with a non-predictable
@@ -175,8 +176,16 @@ if [ $hashonly -ne 1 ]; then
 # package lists
 # -------------
 
-rm -f /tmp/srcidx.$$
-touch /tmp/srcidx.$$
+test -z "$TMPDIR" && TMPDIR=/tmp;
+srcidxdir=`mktemp -d $TMPDIR/genbasedir.XXXXXX 2>/dev/null`
+if [ -z "$srcidxdir" -o ! -d $srcidxdir ]; then
+	srcidxdir=$basedir/.srcidxtmp.$$
+	mkdir -p $srcidxdir
+	if [ ! -d $srcidxdir ]; then
+		echo "error: can't create temp dir" 1>&2
+		exit 1
+	fi
+fi
 
 echo -n "Processing pkglists..."
 
@@ -193,9 +202,9 @@ for comp in $components; do
     fi
 
     if test x$updateinfo = x; then
-    	(cd $basedir; genpkglist $progress $bloat --index /tmp/srcidx.$comp.$$ $topdir $comp)
+    	(cd $basedir; genpkglist $progress $bloat --index $srcidxdir/srcidx.$comp $topdir $comp)
     else
-    	(cd $basedir; genpkglist $progress $bloat --index /tmp/srcidx.$comp.$$ --info $updateinfo $topdir $comp)
+    	(cd $basedir; genpkglist $progress $bloat --index $srcidxdir/srcidx.$comp --info $updateinfo $topdir $comp)
     fi
 
     if [ -f $basedir/pkglist.$comp ]; then
@@ -225,7 +234,7 @@ for comp in $components; do
         rm -f $basedir/pkglist.$comp.bz2.old
     fi
 
-    cat /tmp/srcidx.$comp.$$ >> /tmp/srcidx.$$
+    cat $srcidxdir/srcidx.$comp >> $srcidxdir/srcidx
 
 done
 echo " done"
@@ -251,9 +260,9 @@ for comp in $components; do
     fi
 
     if [ $mapi -ne 0 ]; then
-        (cd $basedir; gensrclist $progress $flat --mapi $srctopdir $comp /tmp/srcidx.$comp.$$)
+        (cd $basedir; gensrclist $progress $flat --mapi $srctopdir $comp $srcidxdir/srcidx.$comp)
     else
-        (cd $basedir; gensrclist $progress $flat $srctopdir $comp /tmp/srcidx.$$)
+        (cd $basedir; gensrclist $progress $flat $srctopdir $comp $srcidxdir/srcidx)
     fi
 
     if [ -f $basedir/srclist.$comp ]; then
@@ -283,13 +292,13 @@ for comp in $components; do
         rm -f $basedir/srclist.$comp.bz2.old
     fi
 
-    rm -f /tmp/srcidx.$comp.$$
+    rm -f $srcidxdir/srcidx.$comp
 done
 echo " done"
 
 fi
 
-rm -f /tmp/srcidx.$$
+rm -rf $srcidxdir
 
 if [ $listonly -ne 0 ]; then
 	if [ $bz2only -eq 1 -a -f $pkglist.$comp ]; then
